
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 9.10 and Phased Array System Toolbox 4.5

% Generated on 16-Dec-2021 11:45:10

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',5,...
'ArrayAxis','y');
%Array.ElementSpacing = 0.5;
sll = 30;
Array.Taper = chebwin(5, sll);

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.FrequencyRange = [0 300000000];
Array.Element = Elem;

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormal',false,...
  'ShowTaper',false,'ShowIndex','None');


options=PatternPlotOptions;
options.Transparency=0.5;
pattern(Array,f,'PatternOptions',p)