% Create a linearArray with dipole element.
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 24-Dec-2021 22:08:05

%% Array Properties 

SubObject = design(dipole, 2100*1e6);
arrayObject = design(linearArray('Element', SubObject), 2100*1e6, SubObject);
arrayObject.NumElements = 5;
arrayObject.AmplitudeTaper = [0.2330 0.7233 1 0.7233 0.2330];
%%
figure;
patternMultiply(arrayObject, PlotFrequency);
%%
arrayObject.AmplitudeTaper = [0.2330 0.7233 1 0.7233 0.2330];
figure;
pattern(arrayObject, PlotFrequency, 'Termination', Termination); 
figure;
arrayFactor(arrayObject,PlotFrequency);
arrayObject.AmplitudeTaper = [1 1 1 1 1];
figure;
pattern(arrayObject, PlotFrequency, 'Termination', Termination); 
figure;
arrayFactor(arrayObject,PlotFrequency);
%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
% Pattern for linearArray
%%
%figure;
PlotFrequency = 2.1*1e9; Termination = 50;
figure;
[PAT, AZ, EL]=pattern(arrayObject, PlotFrequency, 'Termination', Termination); 
phi = AZ';
theta = (90-EL);
MagE = PAT';
patternCustom(MagE,theta,phi);
%%
figure;
arrayFactor(arrayObject,PlotFrequency);
%%
figure;
[PAT2, AZ2, EL2]=arrayFactor(arrayObject,PlotFrequency);
phi2 = AZ2';
theta2 = (90-EL2);
MagE2 = PAT2';

patternCustom(MagE2,theta2,phi2);

%%
%figure;
[PAT1, AZ1, EL1]=pattern(SubObject, PlotFrequency,'Termination', Termination); 
phi1 = AZ1';
theta1 = (90-EL1);
MagE1 = PAT1';
figure;
patternCustom(MagE1,theta1,phi1);
%%
figure;
patternCustom(MagE1.*MagE2,theta2,phi2);
%%


%%
% Azimuth for linearArray
PlotFrequency = 2.1*1e9; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, PlotFrequency, azRange, 0, 'Termination', Termination);
% Elevation for linearArray
PlotFrequency = 2.1*1e9; elRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, PlotFrequency, 0, elRange, 'Termination', Termination);

