% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 27-Dec-2021 16:57:00

%% Antenna Properties 

antennaObject = design(patchMicrostrip, 2100*1e6);
antennaObject.Length = 0.0158;
antennaObject.Width = 0.0351;
antennaObject.Height = 0.0008;
antennaObject.Substrate.Name = 'FR4';
antennaObject.Substrate.EpsilonR = 4.8;
antennaObject.Substrate.LossTangent = 0.026;
antennaObject.Substrate.Thickness = 0.0008;
antennaObject.GroundPlaneLength = 0.03;
antennaObject.GroundPlaneWidth = 0.058;
antennaObject.FeedOffset = [-0.0012, 0.001];
antennaObject.Conductor.Name = 'Copper';
antennaObject.Conductor.Conductivity = 5.96*1e7;
antennaObject.Conductor.Thickness = 3.556e-05;
% Show
figure;
show(antennaObject) 

