% Create a pifa antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 20-Dec-2021 17:40:58

%% Antenna Properties 

p = design(pifa, 2100*1e6);
p.Length = 0.0171;
p.Width = 0.0419;
p.Height = 0.0008;
p.Substrate.Name = 'FR4';
p.Substrate.EpsilonR = 4.8;
p.Substrate.LossTangent = 0.026;
p.Substrate.Thickness = 0.0008;
%p.GroundPlaneLength = 0.1;
%p.GroundPlaneWidth = 0.1;
p.GroundPlaneLength = 0.05;
p.GroundPlaneWidth = 0.05;
p.ShortPinWidth = 0.0419;
p.Conductor.Name = 'Copper';
p.Conductor.Conductivity = 5.96*1e7;
p.Conductor.Thickness = 3.556e-05;
% More properties 
p.PatchCenterOffset=[p.Length/2 0];
%Lfeed0=0.0022;
Lfeed=0.0125;
p.FeedOffset=[p.Length-Lfeed 0];
% Show
figure;
show(p) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2.1*1e9;
% Define frequency range 
freqRange = (1890:21:2310)*1e6;
% impedance
figure;
impedance(p, freqRange)
% sparameter
figure;
s = sparameters(p, freqRange); 
rfplot(s)
% pattern
figure;
pattern(p, plotFrequency)
% azimuth
figure;
patternAzimuth(p, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(p, plotFrequency,0,'Elevation',0:5:360)
% current
figure;
current(p, plotFrequency)
%%
mesh_info=meshconfig(p,'Auto');
disp(strcat('Mesh level : ',string(mesh_info.MaxEdgeLength)))
%%



Lgp=[0.1 0.08 0.07 0.06 0.05 0.04];
Wgp=[0.1 0.08 0.07 0.06 0.05];
%Lgp=[0.06 0.05 0.04];
%Wgp=[0.06 0.05];
clear totale SSS
for i=1:length(Lgp)
    for j=1:length(Wgp)
        
p.GroundPlaneLength = Lgp(i);
p.GroundPlaneWidth = Wgp(j);
SSS=sparameters(p,1.95e9);
totale(j,i)=abs(SSS.Parameters);
    end
end
figure();
contourf(Lgp,Wgp,totale);
figure();
contourf(Lgp,Wgp,20*log(totale))
%%
LGP=0.08;
WGP=0.08;
p.GroundPlaneLength = LGP;
p.GroundPlaneWidth = WGP;
freqRange = (1890:21:2310)*1e6;
figure;
tic
s = sparameters(p, freqRange);
rfplot(s);
text=strcat('GP Length=',string(LGP),', GP Width',string(WGP));
title(text)
toc