% Create a linearArray with helix element.
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 23-Dec-2021 11:32:10

%% Array Properties 

SubObject = design(helix, 2100*1e6);
arrayhelix = design(linearArray('Element', SubObject), 2100*1e6, SubObject);
arrayhelix.NumElements = 5;
arrayhelix.ElementSpacing = 0.0939;

%% Array Analysis 
% Show for linearArray
figure;
show(arrayhelix) 
% Layout for linearArray
figure;
layout(arrayhelix) 
Fhelix = arrayFactor(arrayhelix, 2.1e9);
Gf = Fhelix/(2*Cheb_Currents(1)^2+2*Cheb_Currents(2)^2+Cheb_Currents(3));

%% 
eta_T = 0.71;
Gt = eta_T*times(G0,Gf);
