% Create a linearArray with dipole element.
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 23-Dec-2021 11:25:25

%% Array Properties 
clear all
SubObject = design(dipole, 2100*1e6);
arrayObject = design(linearArray('Element', SubObject), 2100*1e6, SubObject);
arrayObject.NumElements = 5;
arrayObject.ElementSpacing = 0.0939;

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
figure;
arrayFactor(arrayObject, 2.1e9,0:360,0)
figure;
arrayFactor(arrayObject, 2.1e9,0,0:360)
figure;
arrayFactor(arrayObject, 2.1e9,0:360,0,'CoordinateSystem', 'rectangular')
figure;
arrayFactor(arrayObject, 2.1e9,0,0:360,'CoordinateSystem', 'rectangular')
F = arrayFactor(arrayObject, 2.1e9,0,0:360);
