% Create a pifa antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 19-Dec-2021 20:19:56

%% Antenna Properties 

antennaObject = design(pifa, 2100*1e6);
antennaObject.Length = 0.03;
antennaObject.Width = 0.07;
antennaObject.Height = 0.0008;
antennaObject.Substrate.Name = 'FR4';
antennaObject.Substrate.EpsilonR = 4.8;
antennaObject.Substrate.LossTangent = 0.026;
antennaObject.Substrate.Thickness = 0.0008;
antennaObject.GroundPlaneLength = 0.1;
antennaObject.GroundPlaneWidth = 0.1;
antennaObject.ShortPinWidth = 0.07;
antennaObject.FeedOffset = [-0.0036, 0];
antennaObject.Conductor.Name = 'Copper';
antennaObject.Conductor.Conductivity = 5.96*1e7;
antennaObject.Conductor.Thickness = 3.556e-05;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2.1*1e9;
% Define frequency range 
freqRange = (1890:25:2310)*1e6;
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)

