
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 9.10 and Phased Array System Toolbox 4.5

% Generated on 19-Dec-2021 11:27:08

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',5,...
'ArrayAxis','y');
Array.ElementSpacing = 0.0939;
sll = 41;
Array.Taper = chebwin(5, sll);
%Array.Taper=[0.1393  0.7215 1 0.7215 0.1393]';
%Array.Taper=[1 1 1 1 1]';
% Create an isotropic antenna element
%Elem = phased.IsotropicAntennaElement;
%Elem.FrequencyRange = [0 300000000];

% USARE LOAD PER CARICARE L'ANTENNA
Array.Element = p;

% Assign Frequencies and Propagation Speed
Frequency = 2.1e9;
PropagationSpeed = 300000000;


% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormal',false,...
  'ShowTaper',false,'ShowIndex','None');

% Calculate Steering Weights

Freq3D = 2.1e9;
% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 3d graph
format = 'polar';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
 'Type','directivity', 'CoordinateSystem', format,'weights', w(:,1));

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
 'Type', 'directivity', 'CoordinateSystem', format ,'weights', w);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d elevation graph
format = 'polar';
cutAngle = 0;
figure;
pattern(Array, Frequency, cutAngle, -90:90, 'PropagationSpeed', PropagationSpeed,...
 'Type', 'directivity', 'CoordinateSystem', format ,'weights', w);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot U Pattern
format = 'uv';
figure;
pattern(Array, Frequency, -1:0.01:1, 0, 'PropagationSpeed', PropagationSpeed,...
 'Type','directivity','CoordinateSystem', format,'weights', w);

