% Create a linearArray with patchMicrostrip element.
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 27-Dec-2021 13:04:18

%% Array Properties 

SubObject = patchMicrostrip;
arrayObject = linearArray('Element', SubObject);

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 

%%
pr = em.internal.makerectangle(0.5,0.5);
pr1 = em.internal.makerectangle(0.02,0.4);
pr2 = em.internal.makerectangle(0.03,0.008);

ph = em.internal.makecircle(0.05);

pf = em.internal.translateshape(pr2,[0 0.1 0]);

c = customAntennaGeometry('Boundary',{pr',ph',pr1',pf'},...
    'Operation','P1-P2-P3+P4');
figure;
show(c);

